### ISSUE TITLE
Comment/Compliment, not an issue

### ISSUE THREAD

**Issue by SkyeChen-28** [xman2156/TOH#2]
I just wanted to say that it's absolutely beautiful seeing 5 out of 6 of the TV series that you cover on your website are coming out of hiatus soon (or in the case of ML, are already airing new episodes!). I watch all these series except for BCG, though I plan to get around to it someday. I love the fact that you created the hiatus tracker websites and really appreciate the work that you've done maintaining and updating it frequently!

You can close this issue once you've read it :)

**Comment by xman2156** [comment]
Thank you so much! Getting help from people like you keeps me motivated to keep on getting better.
