### ISSUE TITLE
Series Finale Release Date (Cable Forums)

### ISSUE THREAD

**Issue by SkyeChen-28** [xman2156/TOH#6]
Hello again! FYI: Cable Forums has released the air date of the series finale of TOH: https://cabletvt.powerrangermail.net/index.php/topic,6995.0.html?PHPSESSID=44c3ebbb7c4c04b54cf5941537f95bbf

**Comment by xman2156** [comment]
Thanks! I changed it in the table last night but forgot to change the countdown..
